-- ShopEase Oracle schema
-- For Oracle 11g, identity columns are not available. This script uses sequences + triggers.

CREATE TABLE APP_USERS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'CUSTOMER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_USER_ROLE CHECK (ROLE IN ('CUSTOMER','ADMIN'))
);

CREATE SEQUENCE APP_USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER APP_USERS_BI
BEFORE INSERT ON APP_USERS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN :NEW.ID := APP_USERS_SEQ.NEXTVAL; END IF;
    IF :NEW.CREATED_AT IS NULL THEN :NEW.CREATED_AT := SYSTIMESTAMP; END IF;
END;
/

CREATE TABLE PRODUCTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE NUMBER(12,2) NOT NULL,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    IMAGE_URL VARCHAR2(500),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CK_PRODUCT_STOCK CHECK (STOCK >= 0),
    CONSTRAINT CK_PRODUCT_ACTIVE CHECK (ACTIVE IN (0,1))
);

CREATE SEQUENCE PRODUCTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER PRODUCTS_BI
BEFORE INSERT ON PRODUCTS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN :NEW.ID := PRODUCTS_SEQ.NEXTVAL; END IF;
    IF :NEW.CREATED_AT IS NULL THEN :NEW.CREATED_AT := SYSTIMESTAMP; END IF;
END;
/

CREATE TABLE CART_ITEMS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    CONSTRAINT FK_CART_USER FOREIGN KEY(USER_ID) REFERENCES APP_USERS(ID),
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),
    CONSTRAINT UK_CART UNIQUE(USER_ID, PRODUCT_ID),
    CONSTRAINT CK_CART_QTY CHECK (QUANTITY > 0)
);

CREATE SEQUENCE CART_ITEMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER CART_ITEMS_BI
BEFORE INSERT ON CART_ITEMS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN :NEW.ID := CART_ITEMS_SEQ.NEXTVAL; END IF;
END;
/

CREATE TABLE ORDERS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'PLACED' NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID) REFERENCES APP_USERS(ID)
);

CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER ORDERS_BI
BEFORE INSERT ON ORDERS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN :NEW.ID := ORDERS_SEQ.NEXTVAL; END IF;
    IF :NEW.ORDER_DATE IS NULL THEN :NEW.ORDER_DATE := SYSTIMESTAMP; END IF;
END;
/

CREATE TABLE ORDER_ITEMS (
    ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR2(150) NOT NULL,
    PRICE NUMBER(12,2) NOT NULL,
    QUANTITY NUMBER NOT NULL,
    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT FK_ITEM_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE SEQUENCE ORDER_ITEMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER ORDER_ITEMS_BI
BEFORE INSERT ON ORDER_ITEMS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN :NEW.ID := ORDER_ITEMS_SEQ.NEXTVAL; END IF;
END;
/

INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL)
VALUES ('Wireless Headphones','Bluetooth over-ear headphones',1999,20,'/images/headphones.svg');

INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL)
VALUES ('Mechanical Keyboard','RGB mechanical keyboard',2499,15,'/images/keyboard.svg');

INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL)
VALUES ('Smart Watch','Fitness and notification smartwatch',2999,12,'/images/watch.svg');

INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL)
VALUES ('Laptop Backpack','Water resistant office backpack',1499,30,'/images/backpack.svg');

COMMIT;

-- Additional demo catalog: 3 rows/categories (Dresses, Mobiles, Sports Shoes)
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Rose Casual Dress','Comfortable everyday dress with a clean modern fit.',1599,20,'/images/dress-rose.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Midnight Party Dress','Elegant party dress for evening occasions and celebrations.',2499,15,'/images/dress-midnight.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Classic Summer Dress','Lightweight summer dress made for comfortable casual wear.',1299,25,'/images/dress-summer.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Nova X5 Mobile','5G smartphone with a bright display, dual camera and all-day battery.',15999,12,'/images/mobile-nova.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('PixelMax Pro Mobile','Performance-focused smartphone with fast charging and a sharp camera.',22999,10,'/images/mobile-pixel.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('SmartOne Lite Mobile','Affordable smartphone for everyday calls, apps and entertainment.',8999,18,'/images/mobile-lite.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Sprint Pro Sports Shoes','Lightweight running shoes with cushioned support for daily training.',2199,22,'/images/sports-running.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('CourtFlex Sports Shoes','Comfortable sports shoes designed for court and indoor training.',2399,18,'/images/sports-court.svg');
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('TrailGrip Sports Shoes','Durable sports shoes with extra grip for outdoor activities.',2699,16,'/images/sports-trail.svg');
COMMIT;
